#!/bin/bash

output_file="OUTPUT"

config_file="$1"
if [ -z "$config_file" -o ! -f "$config_file" ]; then 
  echo "ERROR: missing configuration file"
  exit 1
fi

if ! xmlpathval.py "$config_file" > "$output_file"; then
  echo "ERROR: $config_file is not valid"
  echo "-----------------------------------------"
  cat "$output_file"
  echo "-----------------------------------------"
  exit 1;
fi

src="$(xmlpathval.py "$config_file" '/sync/@src')"
echo "src=$src"
dst="$(xmlpathval.py "$config_file" '/sync/@dst')"
echo "dst=$dst"

rules="$(xmlpathval.py "$config_file" '/sync/rules[1]/text()')"

# parse the rules
while read line; do
  echo "|$line|"
done < <(echo "$rules")

